spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=todo_db;encrypt=false;trustServerCertificate=true
    username: sa
    password: Todo_Pass123!
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  graphql:
    graphiql:
      enabled: true
    path: /graphql

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.example.todo.infrastructure.persistence
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8080

logging:
  level:
    org.springframework.security: DEBUG
