spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=todo_db;encrypt=false;trustServerCertificate=true
    username: sa
    password: Todo_Pass123!
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  graphql:
    graphiql:
      enabled: true
    path: /graphql

server:
  port: 8080

logging:
  level:
    org.springframework.security: DEBUG
